# Generated by Django 3.0.3 on 2020-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='detail',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
