# Generated by Django 3.0.3 on 2020-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_crud', '0002_auto_20200301_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
