# Generated by Django 3.0.3 on 2020-03-01 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_crud', '0003_auto_20200301_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='detail',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='detail',
            name='profile',
            field=models.ImageField(default='IMAGE', upload_to='profile/'),
        ),
    ]
